"use client";

import React from "react";
import { ArrowUpRight } from 'lucide-react'
import { Download } from "lucide-react";

const About = () => {
  const experiences = [
    {
      title: "Data and Automation Intern",
      company: "Long Tail Ventures, Dubai, UAE",
      duration: "Jul 2025 – Sep 2025",
      role: "Role: Marketing Automation Analyst",
      description:
        "Tools/Technologies: n8n, Python, JavaScript, Web APIs (Google, Meta, Open AI and X)",
      highlights: [
        "Leveraged AI tools and process automation to optimize and accelerate marketing workflows.",
        "Designed and deployed an image generation automation agent that streamlined brand promotion across social media platforms.",
        "Integrated Google, Meta, Open AI and X APIs into automation pipeline to enable seamless multiplatform campaign execution and data synchronization.",
        "Analyzed customer behavior data to generate actionable insights and shared findings to cross-functional teams.",
        "Assisted in the execution and optimization of digital marketing campaigns across multiple online businesses."
      ],
    },
    {
      title: "Data Eng, Mgmt and Governance Analyst",
      company: "Accenture Solutions Pvt Ltd, Chennai, India",
      duration: "Nov 2024 – Jan 2025",
      role: "Role: QA Tester – Data Migration",
      description:
        "Tools/Technologies: Amazon Web Services(AWS), Oracle PL/SQL, Teradata, Informatica,Jira, Confluence, TOSCA",  
      highlights: [
        "Created and executed test cases, documented results, and coordinated defect resolutions with developers.",
        "Performed manual, performance and automated testing, checked for defects and ensured data integrity during PowerCenter to Informatica Cloud migration.",
        "Executed complex SQL queries to compare source and target data, ensuring correct transformation logic.",
        "Performed end to end file based testing, validating structure, format, encoding, file size, consistency and content of .csv, .txt and .xml files generated by the workflows.",
        "Led and co-ordinated with QA team on production deployments ensuring minimal disruption to business operations."
      ],
    },
        {
      title: "Data Eng, Mgmt and Governance Associate",
      company: "Accenture Solutions Pvt Ltd, Chennai, India",
      duration: "Sep 2022 – Nov 2024",
      role: "Role: QA Tester – Data Migration",
      description:
        "Tools/Technologies: Amazon Web Services(AWS), Oracle PL/SQL, Teradata, Informatica,Jira, Confluence, TOSCA",  
      highlights: [
        "On boarded as a member of QA (Quality Assurance) team in Informatica Data Management Cloud (IDMC) Conversion project.",
        "Functionally tested different workflows to ensure data integrity between Informatica PowerCenter and Informatica Data Management Cloud.",
        "Utilized SQL extensively to validate tables, databases and stored procedures in workflows to ensure their functionalities behave the same.",
        "Identified and resolved data mismatches and duplicates through detailed SQL analysis.",
        "Utilized TOSCA, an automation tool to reduce time for testing, scripting and documentation of results"
      ],
    },
  ];
  const education = [
    {
      title: "Middlesex University Dubai",
      company: "MS Data Science",
      duration: "2025 – Present",
      description:
        "",
    },
    {
      title: "Kamaraj College of Engineering and Technology",
      company: "B.E Computer Science and Engineering",
      duration: "2019 – 2022",
      description:
        "CGPA: 8.21"
    },
  ];

  return (
    <section id="about" className="pt-24 pb-12 px-4 md:px-16">
      <div className="max-w-3xl mx-auto text-center mb-10">
        <h2 className="text-4xl md:text-5xl font-extrabold mb-12 text-black dark:text-white">
          About Me
        </h2>
        <p className="text-black dark:text-white text-justify leading-relaxed">
          An aspiring data scientist and a resourceful analyst known for high productivity and efficient
          task completion. Excel in communication, teamwork and adaptability, ensuring seamless
          collaboration and project success. With 2 years of work experience, I am seeking a role which
          allows me to continue learning and perfecting my skills as I provide high-quality work, and
          encourages me to flourish.
        </p>
      </div>
      {/* === Experience Timeline === */}
      <div className="max-w-4xl mx-auto mb-10 px-8 md:px-20 pt--1">
        <h3 className="text-4xl font-semibold mb-10 text-black dark:text-white">
          Experience
        </h3>
        {/* === Vertical Timeline === */}
        <div className="relative border-l border-gray-300 dark:border-gray-700 ml-6">
          {experiences.map((exp, index) => (
            <div key={index} className="relative pl-10 pb-12">
              {/* Timeline Dot */}
              <span className="absolute -left-[7px] top-4 w-3 h-3 bg-gray-800 dark:bg-gray-100 rounded-full"></span>
              {/* === Duration (Left side of timeline) === */}
              <span className="absolute -left-44 top-3 w-36 text-right text-sm text-gray-700 dark:text-gray-300">
                {exp.duration}
              </span>
              {/* === Main Content === */}
              <div className="space-y-2">
                <h4 className="text-lg font-semibold text-black dark:text-white leading-snug">
                  {exp.title}
                </h4>
                <h5 className="text-base font-bold text-black dark:text-white leading-snug">
                  {exp.company}
                </h5>
                <p className="text-black dark:text-white leading-relaxed">
                  {exp.role}
                </p>
                <p className="text-black dark:text-white leading-relaxed">
                  {exp.description}
                </p>
              {/* === Highlights === */}
              <ul className="list-disc list-outside pl-6 text-black dark:text-white space-y-1">
                {exp.highlights.map((item, idx) => (
                  <li key={idx} className="text-justify leading-relaxed">
                    {item}
                  </li>
                ))}
              </ul>
              </div>
            </div>
          ))}
        </div>
      </div>
      {/* === Education Timeline === */}
      <div className="max-w-4xl mx-auto mb-10 px-8 md:px-20 pt--1">
        <h3 className="text-4xl font-semibold mb-10 text-black dark:text-white">
          Education
        </h3>
        {/* === Vertical Timeline === */}
        <div className="relative border-l border-gray-300 dark:border-gray-700 ml-6">
          {education.map((edu, index) => (
            <div key={index} className="relative pl-10 pb-12">
              {/* Timeline Dot */}
              <span className="absolute -left-[7px] top-4 w-3 h-3 bg-gray-800 dark:bg-gray-100 rounded-full"></span>
              {/* === Duration (Left side of timeline) === */}
              <span className="absolute -left-44 top-3 w-36 text-right text-sm text-gray-700 dark:text-gray-300">
                {edu.duration}
              </span>
              {/* === Main Content === */}
              <div className="space-y-2">
                <h4 className="text-lg font-semibold text-black dark:text-white leading-snug">
                  {edu.title}
                </h4>
                <h5 className="text-base font-medium text-black dark:text-white leading-snug">
                  {edu.company}
                </h5>
                <p className="text-black dark:text-white leading-relaxed">
                  {edu.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
      {/* === Resume Buttons === */}
      <div className="flex justify-center gap-6">
        <a
          href="/Andrew_CV.pdf"
          download
          className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all duration-300 bg-black text-white dark:bg-white dark:text-black hover:scale-105 hover:shadow-lg"
        >
          Download Resume
          <Download className="w-5 h-5" />
        </a>
        <a
          href="https://drive.google.com/file/d/1CdrNXftUMnyIqbGCGbyXpuvwm12WSU2L/view?usp=sharing"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all duration-300 bg-blue-600 text-white dark:bg-blue-400 dark:text-black hover:scale-105 hover:shadow-lg"
        >
          View Resume Online
          <ArrowUpRight size={18} />
        </a>
      </div>
    </section>
  );
};

export default About;