"use client";

import React from "react";
import { ArrowUpRight } from 'lucide-react'
import Link from "next/link";
import ScrollReveal from "@/components/ScrollReveal";

const About = () => {
  const experiences = [
    {
      title: "AI Engineer Intern",
      company: "Techies Infotech FZCO",
      duration: "Feb 2026 – Aug 2026",
      role: "Role: AI Engineer Intern",
      description:
        "Tools/Technologies: n8n, Python, Web APIs, Ollama (LLMs), PostgreSQL, Supabase",
      highlights: [
        "Developed AI-powered chatbot POCs using n8n, enhancing website interaction and automating user query handling.",
        "Built web scraping/crawling pipelines using Selenium and Playwright to extract data from internal sources and platforms like flight tracking systems, enabling weekly flight analysis insights.",
        "Designed and implemented an HR Insights Assistant that converts natural language queries into actionable insights using LLMs, improving employee performance analysis.",
        "Integrated LLMs via Ollama to power intelligent workflows for flight trend analysis and HR reporting systems.",
        "Developed backend pipelines using PostgreSQL and Supabase, managing structured data for analytics and AI-driven applications.",
        "Implemented vector databases to store and retrieve employee reviews and organizational data, enabling RAG-based insights generation.",
        "Utilized APIs and automation workflows to connect data sources and deliver scalable AI-driven solutions.",
      ],
    },
    {
      title: "Data and Automation Intern",
      company: "Long Tail Ventures, Dubai, UAE",
      duration: "Jul 2025 – Sep 2025",
      role: "Role: Marketing Automation Analyst",
      description:
        "Tools/Technologies: n8n, Python, JavaScript, Web APIs (Google, Meta, Open AI and X)",
      highlights: [
        "Leveraged AI tools and process automation to optimize and accelerate marketing workflows.",
        "Designed and deployed an image generation automation agent that streamlined brand promotion across social media platforms.",
        "Integrated Google, Meta, Open AI and X APIs into automation pipeline to enable seamless multiplatform campaign execution and data synchronization.",
        "Analyzed customer behavior data to generate actionable insights and shared findings to cross-functional teams.",
        "Assisted in the execution and optimization of digital marketing campaigns across multiple online businesses."
      ],
    },
    {
      title: "Data Eng, Mgmt and Governance Analyst",
      company: "Accenture Solutions Pvt Ltd, Chennai, India",
      duration: "Nov 2024 – Jan 2025",
      role: "Role: QA Tester – Data Migration",
      description:
        "Tools/Technologies: Amazon Web Services(AWS), Oracle PL/SQL, Teradata, Informatica,Jira, Confluence, TOSCA",  
      highlights: [
        "Created and executed test cases, documented results, and coordinated defect resolutions with developers.",
        "Performed manual, performance and automated testing, checked for defects and ensured data integrity during PowerCenter to Informatica Cloud migration.",
        "Executed complex SQL queries to compare source and target data, ensuring correct transformation logic.",
        "Performed end to end file based testing, validating structure, format, encoding, file size, consistency and content of .csv, .txt and .xml files generated by the workflows.",
        "Led and co-ordinated with QA team on production deployments ensuring minimal disruption to business operations."
      ],
    },
        {
      title: "Data Eng, Mgmt and Governance Associate",
      company: "Accenture Solutions Pvt Ltd, Chennai, India",
      duration: "Sep 2022 – Nov 2024",
      role: "Role: QA Tester – Data Migration",
      description:
        "Tools/Technologies: Amazon Web Services(AWS), Oracle PL/SQL, Teradata, Informatica,Jira, Confluence, TOSCA",  
      highlights: [
        "On boarded as a member of QA (Quality Assurance) team in Informatica Data Management Cloud (IDMC) Conversion project.",
        "Functionally tested different workflows to ensure data integrity between Informatica PowerCenter and Informatica Data Management Cloud.",
        "Utilized SQL extensively to validate tables, databases and stored procedures in workflows to ensure their functionalities behave the same.",
        "Identified and resolved data mismatches and duplicates through detailed SQL analysis.",
        "Utilized TOSCA, an automation tool to reduce time for testing, scripting and documentation of results"
      ],
    },
  ];
  const education = [
    {
      title: "Middlesex University Dubai",
      company: "MS Data Science",
      duration: "2025 – Present",
      description: "",
    },
    {
      title: "Kamaraj College of Engineering and Technology",
      company: "B.E Computer Science and Engineering",
      duration: "2019 – 2022",
      description: "CGPA: 8.21",
    },
    {
      title: "Adhyapana School CBSE",
      company: "Higher Secondary Education",
      duration: "2016 – 2018",
      description: "CGPA: 8.0",
    },
    {
      title: "Adhyapana School CBSE",
      company: "Senior Secondary Education",
      duration: "2014 – 2016",
      description: "CGPA: 9.0",
    },
  ];

  return (
    <section id="about" className="pt-24 pb-12 px-4 md:px-16">
      <div className="max-w-3xl mx-auto text-center mb-10">
        <h2 className="text-4xl md:text-5xl font-extrabold mb-12 text-black dark:text-white">
          About Me
        </h2>
        <p className="text-black dark:text-white text-justify leading-relaxed">
          An aspiring data scientist and a resourceful analyst known for high productivity and efficient
          task completion. Excel in communication, teamwork and adaptability, ensuring seamless
          collaboration and project success. With 2 years of work experience, I am seeking a role which
          allows me to continue learning and perfecting my skills as I provide high-quality work, and
          encourages me to flourish.
        </p>
      </div>
      {/* === Experience Timeline (Alternating) === */}
      <div id="experience" className="max-w-5xl mx-auto mb-10 px-4 md:px-8 scroll-mt-24">
        <h3 className="text-4xl font-semibold mb-14 text-center text-black dark:text-white">
          Experience
        </h3>
        {/* === Center-line Timeline === */}
        <div className="relative">
          {/* Center vertical line */}
          <div className="absolute left-1/2 -translate-x-1/2 top-0 bottom-0 w-px bg-gray-300 dark:bg-gray-700 hidden md:block" />
          {/* Mobile left line */}
          <div className="absolute left-4 top-0 bottom-0 w-px bg-gray-300 dark:bg-gray-700 md:hidden" />

          {experiences.map((exp, index) => {
            const isLeft = index % 2 === 0;
            return (
              <div key={index} className="relative mb-12">
                {/* Timeline Dot (center on desktop, left on mobile) */}
                <span className="absolute left-[13px] md:left-1/2 md:-translate-x-1/2 top-6 w-3 h-3 bg-gray-800 dark:bg-gray-100 rounded-full z-10" />

                {/* Content card */}
                <ScrollReveal
                  variant={isLeft ? "fadeRight" : "fadeLeft"}
                  duration={700}
                  delay={index * 100}
                >
                  <div className={`ml-10 md:ml-0 md:w-[45%] ${isLeft ? 'md:mr-auto md:pr-8' : 'md:ml-auto md:pl-8'}`}>
                    <span className="inline-block text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">
                      {exp.duration}
                    </span>
                    <div className="space-y-2 rounded-xl border border-gray-200 dark:border-gray-700/50 bg-white/5 backdrop-blur-sm p-5">
                      <h4 className="text-lg font-semibold text-black dark:text-white leading-snug">
                        {exp.title}
                      </h4>
                      <h5 className="text-base font-bold text-black dark:text-white leading-snug">
                        {exp.company}
                      </h5>
                      <p className="text-black dark:text-white leading-relaxed">
                        {exp.role}
                      </p>
                      <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
                        {exp.description}
                      </p>
                      <ul className="list-disc list-outside pl-6 text-black dark:text-white space-y-1">
                        {exp.highlights.map((item, idx) => (
                          <li key={idx} className="text-sm text-justify leading-relaxed">
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </ScrollReveal>
              </div>
            );
          })}
        </div>
      </div>
      {/* === Education Timeline (Alternating) === */}
      <div id="education" className="max-w-5xl mx-auto mb-10 px-4 md:px-8 scroll-mt-24">
        <h3 className="text-4xl font-semibold mb-14 text-center text-black dark:text-white">
          Education
        </h3>
        <div className="relative">
          {/* Center vertical line */}
          <div className="absolute left-1/2 -translate-x-1/2 top-0 bottom-0 w-px bg-gray-300 dark:bg-gray-700 hidden md:block" />
          {/* Mobile left line */}
          <div className="absolute left-4 top-0 bottom-0 w-px bg-gray-300 dark:bg-gray-700 md:hidden" />

          {education.map((edu, index) => {
            const isLeft = index % 2 === 0;
            return (
              <div key={index} className="relative mb-12">
                {/* Timeline Dot */}
                <span className="absolute left-[13px] md:left-1/2 md:-translate-x-1/2 top-6 w-3 h-3 bg-gray-800 dark:bg-gray-100 rounded-full z-10" />

                <ScrollReveal
                  variant={isLeft ? "fadeRight" : "fadeLeft"}
                  duration={700}
                  delay={index * 100}
                >
                  <div className={`ml-10 md:ml-0 md:w-[45%] ${isLeft ? 'md:mr-auto md:pr-8' : 'md:ml-auto md:pl-8'}`}>
                    <span className="inline-block text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">
                      {edu.duration}
                    </span>
                    <div className="space-y-2 rounded-xl border border-gray-200 dark:border-gray-700/50 bg-white/5 backdrop-blur-sm p-5">
                      <h4 className="text-lg font-semibold text-black dark:text-white leading-snug">
                        {edu.title}
                      </h4>
                      <h5 className="text-base font-bold text-black dark:text-white leading-snug">
                        {edu.company}
                      </h5>
                      {edu.description && (
                        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
                          {edu.description}
                        </p>
                      )}
                    </div>
                  </div>
                </ScrollReveal>
              </div>
            );
          })}
        </div>
      </div>
      {/* === Resume Buttons === */}
      <div className="flex justify-center gap-6">
        <Link
          href="/projects"
          className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all duration-300 bg-black text-white dark:bg-white dark:text-black hover:scale-105 hover:shadow-lg"
        >
          View Projects
          <ArrowUpRight size={18} />
        </Link>
        <a
          href="https://drive.google.com/file/d/1CdrNXftUMnyIqbGCGbyXpuvwm12WSU2L/view?usp=sharing"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all duration-300 bg-blue-600 text-white dark:bg-blue-400 dark:text-black hover:scale-105 hover:shadow-lg"
        >
          View Resume Online
          <ArrowUpRight size={18} />
        </a>
      </div>
    </section>
  );
};

export default About;